
# Site settings
title: Mojatatu Networks 
email: info@mojatatu.com

authors:
  hadi:
    name: Jamal H. Salim
    display_name: Jamal
    email: hadi@mojatatu.com
    web: http://www.mojatatu.com

# Building settings
markdown: kramdown

